api_key: devkey
api_secret: secret
ws_url: ws://host.docker.internal:7880
insecure: true
redis:
  address: host.docker.internal:6379
  
# Health check port
health_port: 6000

# Template for file output
file_output:
  local: true
  upload_config: 
    type: local
